### PR TITLE
Added support to test in GitLab CI

### PR DESCRIPTION
**Pull request by brodock**
Included Rails 5.1 and 5.2 to the stable test matrix

### CODE REVIEW

**Review by ch1ago — COMMENTED** [review]
Commit Review: OK - Migrate to Factory Bot and upgrade to latest 4.x

**Review by ch1ago — COMMENTED** [review]
Commit Review: OK - Added support to test in GitLab CI

**Review by ch1ago — COMMENTED** [review]
Commit Review: OK - Fixes for Rails 5 support

**Review by ch1ago — COMMENTED** [review]
Commit Review: OK - Fix codestyle violatons

**Review by ch1ago — COMMENTED** [review]
Commit Review: OK - Fix device detection spec

**Comment by brodock** [comment]
fixed GitLab CI cache key

**Pull request merged**
